/*************************************************************
@Name: APTS_UserDetails
@Author: Jinal Bhatt / Karsan Prajapati (@apttus)
@CreateDate:14/03/2018
@purpose: This class is a place holder for User Details Wrapper class.
******************************************************************/
Public class APTSMD_UserDetails{
    Public String Email {get; set;} // Store User EmailId
    Public String UserFullName {get; set;} // Store User Full Name
    Public String UserLanguage {get; set;} //Store User Language
    Public String UserLocale {get; set;} //Store User Locale
    Public String UserName {get; set;} // Store UserName to Login
    Public String OrgID {get; set;} // Store Organization Id
    Public String OrgName {get; set;} // Store Organization Name
    Public String SessionId {get; set;} // Store Session Id
    Public String BaseURL {get; set;} // Store Domain Name
    Public String UserTimeZone {get; set;} // Store User TimeZone
    Public String PlaceHolder {get;set;} // Identify SFDC / AIC
    Public Id UserId {get; set;} // Store User Id
    Public String ProfilePhoto {get; set;} // Store Profile Photo
    
}