public class APTS_TaxConstants {
    public static final string BASE_URL = Label.APTS_Avalara_Tax_Integration;
    public static final string USERNAME = 'pmali@apttus.com';
    public static final string PASSWORD = 'Apttus@123';
    public static final string ACCOUNT_ID = '2000121716';
    public static final string LICENCE_KEY = '50265242AB855AB2';
    public static final decimal TAX_RATE_DEFAULT = 0.1;
    public static final boolean CALCULATE_FOR_STATES = true;
    public static final string TAX_APPLIESTO_NET_PRICE = 'Net Price';
    public static final integer CURRENCY_DECIAML_PLACES = 2;
}